# Generated by Django 4.1.3 on 2022-11-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='symbol',
            field=models.CharField(default='example', max_length=50),
            preserve_default=False,
        ),
    ]
