# Generated by Django 4.1.3 on 2022-11-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_stock_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
